"""Candidate pool generation and collection (new; Section 7 stage (i)).

The certification layer does NOT re-run the first paper's robust WEE
optimizer.  Candidate configurations are generated by a decoupled,
lightweight protocol on the shared nominal channel drop:

  1. RIS phase profile: a fraction ``align_frac`` of the elements takes the
     cascaded-channel-aligned quantized phase (two-pass heuristic), the rest
     are drawn uniformly from the B-bit discrete set Q_B (Eq. (1));
  2. beamforming directions: reused MRT or intra-cell RZF initializers;
  3. power control: a worst-case fixed-point iteration (Cauchy-Schwarz
     bounds over the per-user uncertainty ball) that meets a chosen design
     SINR target ``gamma_d >= gamma_bar`` with design radius ``eps_d``
     (eps_d = 0 -> nominal design, eps_d = epsilon -> robust design);

followed by the reused nominal QoS feasibility check and WEE evaluation.
Candidates whose power control diverges or exceeds the per-BS budget are
discarded.  The knobs (align_frac, bits, direction type, gamma_d, eps_d) are
randomized per candidate to obtain a diverse feasible pool in the
WEE-robustness plane, as required by Experiment 2.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from .ris_base import (
    SimConfig,
    ChannelDrop,
    effective_channels,
    compute_sinr_from_H,
    quantize_theta,
    random_theta,
    user_weights,
    utility_power_wee_from_H,
)
from .ris_base.models import phase_indices


# ---------------------------------------------------------------------- #
# Candidate container                                                    #
# ---------------------------------------------------------------------- #

@dataclass
class Candidate:
    index: int
    seed: int
    bits: int
    direction_kind: str          # "mrt" | "rzf"
    align_frac: float
    design_gamma: float          # design SINR target (linear)
    design_eps: float            # design uncertainty radius (0 = nominal)
    w: np.ndarray                # (L,K,M)
    theta: np.ndarray            # (N,)
    H: np.ndarray                # (L,L,K,M) nominal equivalent channels
    sinr_nominal: np.ndarray     # (L,K)
    wee: float
    U: float
    V: float
    power_per_bs: np.ndarray     # (L,)
    qos_feasible: bool
    # Optional post-convergence power scaling (1 = power-minimal design)
    power_slack: float = 1.0
    # Filled by the certification stage
    r_cert: float = float("nan")
    cert_info: Dict = field(default_factory=dict)

    def to_record(self) -> Dict:
        return {
            "index": self.index,
            "seed": self.seed,
            "bits": self.bits,
            "direction_kind": self.direction_kind,
            "align_frac": self.align_frac,
            "design_gamma": self.design_gamma,
            "design_eps": self.design_eps,
            "power_slack": self.power_slack,
            "min_sinr_nominal": float(np.min(self.sinr_nominal)),
            "wee": self.wee,
            "U": self.U,
            "V": self.V,
            "power_per_bs": self.power_per_bs.tolist(),
            "qos_feasible": self.qos_feasible,
            "r_cert": self.r_cert,
            "cert_info": self.cert_info,
        }


# ---------------------------------------------------------------------- #
# RIS phase construction                                                 #
# ---------------------------------------------------------------------- #

def cascaded_aligned_theta(
    drop: ChannelDrop,
    directions: np.ndarray,
    omega: np.ndarray,
    bits: int,
    cfg: SimConfig,
) -> np.ndarray:
    """Two-pass heuristic: phases aligning the weighted cascaded gains.

    With serving-cell MRT/RZF directions f_lk, the cascaded gain of element
    i for user (l,k) contributes  h_ru[l,k,i] * (h_br[l,i,:] @ f_lk);
    choosing theta_i = angle(sum_{lk} omega_lk * that product) aligns the
    phases of the users' cascaded responses and is quantized to Q_B.
    """
    L, K, M, N = cfg.L, cfg.K, cfg.M, cfg.N
    h_br = drop.h_br                    # (L,N,M)
    h_ru = drop.h_ru                    # (L,K,N)
    # z[i] = sum_{l,k} omega_lk * h_ru[l,k,i] * (h_br[l,i,:] @ f_lk)
    serv = np.einsum("lim,lkm->lik", h_br, directions, optimize=True)  # (L,N,K)
    z = np.einsum("lk,lki,lik->i", omega, h_ru, serv, optimize=True)   # (N,)
    return quantize_theta(np.exp(1j * np.angle(z)), bits)


def mixture_theta(
    drop: ChannelDrop,
    directions: np.ndarray,
    omega: np.ndarray,
    bits: int,
    align_frac: float,
    cfg: SimConfig,
    rng: np.random.Generator,
    align_jitter: float = 0.0,
) -> np.ndarray:
    """align_frac of the elements take (jittered) aligned phases, rest random.

    ``align_jitter`` is a half-width in radians applied to the aligned
    elements' target angles before quantization; it provides pool diversity
    at high align fractions (imperfect/near-aligned phase profiles).
    """
    h_br = drop.h_br
    h_ru = drop.h_ru
    serv = np.einsum("lim,lkm->lik", h_br, directions, optimize=True)
    z = np.einsum("lk,lki,lik->i", omega, h_ru, serv, optimize=True)
    ang = np.angle(z)
    if align_jitter > 0.0:
        ang = ang + rng.uniform(-align_jitter, align_jitter, size=cfg.N)
    theta_a = quantize_theta(np.exp(1j * ang), bits)
    theta_r = random_theta(cfg.N, bits, rng)
    n_aligned = int(round(float(align_frac) * cfg.N))
    mask = np.zeros(cfg.N, dtype=bool)
    if n_aligned > 0:
        mask[rng.choice(cfg.N, size=n_aligned, replace=False)] = True
    return np.where(mask, theta_a, theta_r)


# ---------------------------------------------------------------------- #
# Beamforming directions and worst-case power control                    #
# ---------------------------------------------------------------------- #

def unit_directions(
    H: np.ndarray,
    kind: str,
    cfg: SimConfig,
    rng: Optional[np.random.Generator] = None,
) -> np.ndarray:
    """Unit-norm beamforming directions.

    Supported kinds:
      - "mrt"     : maximum-ratio transmission toward each user's own
                    serving-cell equivalent channel (reused initializer);
      - "rzf"     : intra-cell regularized zero-forcing (reused initializer);
      - "zf_full" : centralized ZF that additionally nulls each beam's
                    RIS-mediated leakage onto the other cells' users
                    (feasible for M >= L*K-1; the workhorse of the pool
                    protocol because the shared RIS otherwise couples the
                    two cells at full strength).
    """
    L, K, M = cfg.L, cfg.K, cfg.M
    f = np.zeros((L, K, M), dtype=np.complex128)
    if kind == "zf_full":
        for l in range(L):
            for k in range(K):
                null_cols = [H[l, l, j] for j in range(K) if j != k]
                for lp in range(L):
                    if lp != l:
                        null_cols += [H[l, lp, kp] for kp in range(K)]
                U = np.column_stack(null_cols)
                h = H[l, l, k].astype(np.complex128, copy=True)
                v = U.conj().T @ h
                h -= U @ np.linalg.lstsq(U.conj().T @ U, v, rcond=None)[0]
                nrm = np.linalg.norm(h)
                f[l, k] = h / nrm if nrm > 1e-12 else np.eye(M)[k % M]
        return f
    if kind == "mrt":
        for l in range(L):
            for k in range(K):
                h = H[l, l, k]
                nrm = np.linalg.norm(h)
                f[l, k] = h / nrm if nrm > 1e-14 else (
                    rng.standard_normal(M) + 1j * rng.standard_normal(M)
                ) / np.sqrt(2.0) if rng is not None else np.eye(M)[k % M]
    elif kind == "rzf":
        reg = cfg.noise_power_watt / max(cfg.p_max_watt, 1e-12)
        for l in range(L):
            A = np.column_stack([H[l, l, k] for k in range(K)])
            V = np.linalg.solve(A @ A.conj().T + reg * np.eye(M), A)
            for k in range(K):
                nrm = np.linalg.norm(V[:, k])
                f[l, k] = V[:, k] / nrm if nrm > 1e-14 else np.eye(M)[k % M]
    else:
        raise ValueError(f"unknown direction kind {kind}")
    # normalize any residual column
    for l in range(L):
        for k in range(K):
            nrm = np.linalg.norm(f[l, k])
            if nrm < 1e-14:
                f[l, k] = np.eye(M)[k % M]
            else:
                f[l, k] = f[l, k] / nrm
    return f


def power_control_worst_case(
    H: np.ndarray,
    f: np.ndarray,
    cfg: SimConfig,
    gamma_d: float,
    eps_d: float,
    max_iter: int = 400,
    tol: float = 1.0e-10,
) -> Tuple[Optional[np.ndarray], Dict]:
    """Worst-case (Cauchy-Schwarz) QoS power control at design radius eps_d.

    Fixed point over powers p >= 0 with unit directions f:

      p_lk <- gamma_d * ( sum_{(i,j)!=(l,k)} p_ij (|H[i,l,k].f_ij| + r_lk)^2
                          + sigma^2 )
               / ( |H[l,l,k].f_lk| - r_lk )^2 ,   r_lk = eps_d ||h_lk||.

    Returns (p, info); p is None when the desired-gain bound degenerates
    (|h^H f| <= r_lk) or the iteration diverges.
    """
    L, K = cfg.L, cfg.K
    # scalar gains g[l,k,i,j] = <H[i,l,k], f[i,j]> = vdot(H[i,l,k], f[i,j])
    g = np.einsum("ilkm,ijm->lkij", H.conj(), f, optimize=True)
    # per-user relative radius on the aggregate stacked channel
    r = np.zeros((L, K), dtype=float)
    for l in range(L):
        for k in range(K):
            h_stack = H[:, l, k, :].reshape(-1)
            if cfg.relative_radius:
                r[l, k] = eps_d * max(float(np.linalg.norm(h_stack)), cfg.radius_floor)
            else:
                r[l, k] = eps_d

    # desired gains: g[l,k,l,k] = vdot(H[l,l,k], f[l,k])
    desired = np.abs(
        np.einsum(
            "lkm,lkm->lk",
            H[np.arange(L), np.arange(L)].conj(),
            f[np.arange(L)],
            optimize=True,
        )
    )
    gain_floor = 1e-12
    den_base = desired - r
    if np.any(den_base <= gain_floor):
        return None, {"reason": "desired_gain_degenerate"}

    cross = np.abs(g) + r[:, :, None, None]      # worst-case cross gains
    p = np.full((L, K), 1e-6)
    diverged = False
    it = 0
    for it in range(1, max_iter + 1):
        p_new = np.empty_like(p)
        for l in range(L):
            for k in range(K):
                mask = np.ones((L, K), dtype=bool)
                mask[l, k] = False
                inter = float(
                    np.sum(p[mask] * (cross[l, k, :, :] ** 2)[mask])
                )
                p_new[l, k] = (
                    gamma_d * (inter + cfg.noise_power_watt)
                    / max(den_base[l, k] ** 2, gain_floor)
                )
        delta = np.max(np.abs(p_new - p)) / max(np.max(p), 1e-30)
        p = p_new
        if not np.all(np.isfinite(p)) or np.max(p) > 1e6:
            diverged = True
            break
        if delta < tol:
            break
    if diverged:
        return None, {"reason": "diverged", "iters": it}

    per_bs = p.sum(axis=1)
    if np.any(per_bs > cfg.p_max_watt):
        return None, {"reason": "power_budget_exceeded", "per_bs": per_bs.tolist()}
    return p, {"reason": "converged", "iters": it, "per_bs": per_bs.tolist()}


# ---------------------------------------------------------------------- #
# Candidate generation and pool construction                             #
# ---------------------------------------------------------------------- #

def generate_candidate(
    drop: ChannelDrop,
    cfg: SimConfig,
    cert_cfg,
    seed: int,
) -> Tuple[Optional[Candidate], str]:
    """One candidate attempt; returns (candidate_or_None, reject_reason)."""
    rng = np.random.default_rng(seed)
    kind = cert_cfg.direction_choices[rng.integers(0, len(cert_cfg.direction_choices))]
    align_frac = float(cert_cfg.align_frac_grid[rng.integers(0, len(cert_cfg.align_frac_grid))])
    align_jitter = float(cert_cfg.align_jitter_grid[rng.integers(0, len(cert_cfg.align_jitter_grid))])
    bits = int(cert_cfg.bits_grid[rng.integers(0, len(cert_cfg.bits_grid))])
    gamma_mult = float(cert_cfg.design_gamma_mult[rng.integers(0, len(cert_cfg.design_gamma_mult))])
    eps_d = float(cert_cfg.design_eps_grid[rng.integers(0, len(cert_cfg.design_eps_grid))])
    gamma_d = gamma_mult * cfg.gamma

    omega = user_weights(drop, cfg)

    # Pass 1: directions with an arbitrary theta, then aligned-phase mixture.
    f0 = unit_directions(effective_channels(drop, np.ones(cfg.N, dtype=complex), cfg), kind, cfg, rng)
    theta = mixture_theta(drop, f0, omega, bits, align_frac, cfg, rng, align_jitter=align_jitter)
    H = effective_channels(drop, theta, cfg)

    # Pass 2: final directions on the realized theta, then power control.
    f = unit_directions(H, kind, cfg, rng)
    p, info = power_control_worst_case(H, f, cfg, gamma_d, eps_d,
                                       max_iter=cert_cfg.pc_max_iter,
                                       tol=cert_cfg.pc_tol)
    if p is None:
        return None, f"power:{info.get('reason', 'unknown')}"

    # Optional non-minimal power operation (slack > 1): wasteful designs
    # that trade WEE for extra SINR margin, enriching the upper-left region
    # of the WEE-robustness plane (Section 9 pool-diversity protocol).
    slack = float(
        cert_cfg.power_slack_grid[rng.integers(0, len(cert_cfg.power_slack_grid))]
    )
    if slack != 1.0:
        p = p * slack
        if np.any(p.sum(axis=1) > cfg.p_max_watt):
            return None, "power:slack_budget"

    w = f * np.sqrt(p)[:, :, None]

    # Reused nominal QoS check and WEE evaluation.
    sinr = compute_sinr_from_H(w, H, cfg)
    qos_ok = bool(np.min(sinr) >= cfg.gamma - 1e-6)
    if not qos_ok:
        return None, "qos:not_met"

    U, V, wee = utility_power_wee_from_H(w, theta, drop, H, cfg, omega=omega)
    return Candidate(
        index=-1,
        seed=seed,
        bits=bits,
        direction_kind=kind,
        align_frac=align_frac,
        design_gamma=gamma_d,
        design_eps=eps_d,
        power_slack=slack,
        w=w,
        theta=theta,
        H=H,
        sinr_nominal=sinr,
        wee=float(wee),
        U=float(U),
        V=float(V),
        power_per_bs=p.sum(axis=1),
        qos_feasible=True,
    ), "ok"


def build_pool(
    drop: ChannelDrop,
    cfg: SimConfig,
    cert_cfg,
) -> Tuple[List[Candidate], Dict]:
    """Build the candidate pool on the shared nominal drop (Section 9)."""
    rng = np.random.default_rng(cert_cfg.pool_seed)
    pool: List[Candidate] = []
    seen = set()
    stats = {
        "attempts": 0,
        "accepted": 0,
        "rejected_unique": 0,
        "rejected_qos_power": 0,
        "reject_reasons": {},
    }
    seed = int(cert_cfg.pool_seed)
    while (len(pool) < cert_cfg.pool_target_size
           and stats["attempts"] < cert_cfg.pool_max_attempts):
        stats["attempts"] += 1
        seed += 1
        cand, reason = generate_candidate(drop, cfg, cert_cfg, seed)
        if cand is None:
            stats["rejected_qos_power"] += 1
            stats["reject_reasons"][reason] = stats["reject_reasons"].get(reason, 0) + 1
            continue
        key = (
            tuple(phase_indices(cand.theta, cand.bits).tolist()),
            cand.bits,
            cand.direction_kind,
            round(cand.design_gamma, 6),
            round(cand.design_eps, 6),
            round(cand.power_slack, 6),
        )
        if key in seen:
            stats["rejected_unique"] += 1
            continue
        seen.add(key)
        cand.index = len(pool)
        pool.append(cand)
        stats["accepted"] += 1

    return pool, stats


# ---------------------------------------------------------------------- #
# Pool serialization                                                     #
# ---------------------------------------------------------------------- #

def save_pool(path_prefix: str, pool: List[Candidate], meta: Dict) -> Tuple[str, str]:
    """Save candidate arrays (.npz) and metrics (.json) under one prefix."""
    prefix = Path(path_prefix)
    prefix.parent.mkdir(parents=True, exist_ok=True)
    npz_path = prefix.with_suffix(".npz")
    json_path = prefix.with_suffix(".json")
    arrays = {
        "w": np.stack([c.w for c in pool]),
        "theta": np.stack([c.theta for c in pool]),
        "H": np.stack([c.H for c in pool]),
        "sinr": np.stack([c.sinr_nominal for c in pool]),
    }
    np.savez_compressed(npz_path, **arrays)
    payload = {"meta": meta, "candidates": [c.to_record() for c in pool]}
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
    return str(npz_path), str(json_path)


def load_pool(path_prefix: str) -> Tuple[List[Candidate], Dict]:
    prefix = Path(path_prefix)
    data = np.load(prefix.with_suffix(".npz"))
    with open(prefix.with_suffix(".json"), "r", encoding="utf-8") as fh:
        payload = json.load(fh)
    pool: List[Candidate] = []
    for i, rec in enumerate(payload["candidates"]):
        pool.append(
            Candidate(
                index=rec["index"],
                seed=rec["seed"],
                bits=rec["bits"],
                direction_kind=rec["direction_kind"],
                align_frac=rec["align_frac"],
                design_gamma=rec["design_gamma"],
                design_eps=rec["design_eps"],
                power_slack=rec.get("power_slack", 1.0),
                w=data["w"][i],
                theta=data["theta"][i],
                H=data["H"][i],
                sinr_nominal=data["sinr"][i],
                wee=rec["wee"],
                U=rec["U"],
                V=rec["V"],
                power_per_bs=np.asarray(rec["power_per_bs"]),
                qos_feasible=rec["qos_feasible"],
                r_cert=rec["r_cert"],
                cert_info=rec.get("cert_info", {}),
            )
        )
    return pool, payload.get("meta", {})
